// <auto-generated />
namespace LeapList.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _9820151 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_9820151));
        
        string IMigrationMetadata.Id
        {
            get { return "201509081923532_9.8.2015.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
